### ISSUE TITLE
无法删除 wraplish 添加的空格及后面的汉字

### ISSUE THREAD

**Issue by kimim** [manateelazycat/wraplish#1]
如果光标落在字母和中文之间添加的空格处，就无法用 `C-d` 删除当前 wraplish 添加的空格以及后面的汉字。

**Comment by manateelazycat** [comment]
wraplish 一般用于Markdown文档写作， 本来就是强迫症插件， 既然选择添加空格， 为啥又要删除呢？

**Comment by kimim** [comment]
但是因为没法删掉这个空格，就无法继续 C-d 后面的汉字。
因为 C-d 空格之后，空格又被添加了回来。

我再习惯一下看看。

**Comment by manateelazycat** [comment]
最新版， 如果当前是删除命令就展示不格式化buffer， 应该解决了这个问题了。
