### ISSUE TITLE
Fix extra space between `https:` and `//`

### ISSUE THREAD

**Issue by clsty** [manateelazycat/wraplish#8]
[commit 5029e6](https://github.com/manateelazycat/wraplish/commit/5029e608f1fbaa001e433f28cfa1288a4ccc9092) 通过在 `https:` 与 `//` 之间加空格，破坏了 README 里的所有链接。

我建议重新检查此 commit 对 wraplish 造成的影响，因为它很可能正是这些链接被同时破坏的原因。

此外，本仓库并未开启 Wiki，README 里的 Wiki 链接也是无效的。

**Comment by manateelazycat** [comment]
按道理 https 跟的是英文冒号， 中文冒号都会加空格。

Anyway， 我加了个补丁修复这个问题 https://github.com/manateelazycat/wraplish/commit/949dbccbcba101d2c27827ceb157736cbf2afa23
